"""initial

Revision ID: ca279684a0d9
Revises: d9507454e5ee
Create Date: 2020-11-07 22:26:35.172402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca279684a0d9'
down_revision = 'd9507454e5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
